sudo: require
services:
    - docker


before_install:
    - docker build -t dockerleho8808g/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true dockerleho8808g/docker-react npm run test